services:
  backend:
    build: 
      context: .
      target: prod
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - psql_data:/var/lib/postgresql/data

volumes:
  psql_data:
